# Generated by Django 5.1.4 on 2025-01-05 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rezerwacja',
            options={},
        ),
    ]
