# Generated by Django 5.1.4 on 2025-01-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_system', '0002_alter_rezerwacja_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rezerwacja',
            options={'managed': False},
        ),
    ]
