# Generated by Django 5.1.4 on 2025-01-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_system', '0003_alter_rezerwacja_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingspot',
            options={'managed': True},
        ),
    ]
