# Generated by Django 5.1.4 on 2025-01-18 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_system', '0004_alter_parkingspot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uzytkownik',
            options={},
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='atrybut',
            field=models.ForeignKey(db_column='atrybut', default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='parking_system.atrybuty'),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='parking',
            field=models.ForeignKey(db_column='Parking_id', default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='parking_system.parking'),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='status',
            field=models.CharField(default='dostępne', max_length=20),
        ),
    ]
