# Generated by Django 5.1.4 on 2025-01-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_system', '0005_alter_uzytkownik_options_parkingspot_atrybut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzytkownik',
            name='imie',
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='nazwisko',
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='telefon',
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='typ',
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='first_name',
            field=models.CharField(db_column='imie', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='last_name',
            field=models.CharField(db_column='nazwisko', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='password',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='phone',
            field=models.CharField(db_column='telefon', default='unknown', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='user_type',
            field=models.CharField(db_column='typ', default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
